name: fetch Web & convert to Markdown
on:
  issues:
    types:
      - opened
      - edited
jobs:
  fetch_convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: freeCodeCamp-China/article-webpage-to-markdown-action@simplify-code-structure
        with:
          githubToken: ${{ github.token }}
          newsLink: "${{ github.event.issue.Body }}"
          markDownFilePath: "./articles/"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "${{ github.event.issue.title }}"
