name: fetch Web & convert to Markdown
on:
  issues:
    types:
      - opened
jobs:
  fetch_convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: freeCodeCamp-China/article-webpage-to-markdown-action@v0.2.0-rc.0
        with:
          githubToken: ${{ github.token }}
          newsLink: "${{ github.event.issue.Body }}"
          markDownFilePath: "./articles/"

      - uses: stefanzweifel/git-auto-commit-action@v5
